# Start Times dict with the needed start time params associated with each EDF
# Data Previews: https://archive.physionet.org/cgi-bin/atm/ATM
# Set Input:
#    Set Database to CAP Sleep Database (capslpdb)
#    Set Record to the Correct Individual
# Set Toolbox to "Export Signals as CSV"
# You should be able to see the start time of the study.

# Copy the start time parameters below:

startTimes = {
    "n3": {
        "study_start_year": 2009,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 15,
        "study_start_second": 42,
    },
    "n10": {
        "study_start_year": 2008,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 24,
        "study_start_second": 52,
    },
    "ins2": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 18,
        "study_start_min": 25,
        "study_start_second": 37,
    },
    "ins5": {
        "study_start_year": 2011,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 17,
        "study_start_min": 58,
        "study_start_second": 48,
    },
    "ins6": {
        "study_start_year": 2002,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 18,
        "study_start_min": 46,
        "study_start_second": 57,
    },
    "ins7": {
        "study_start_year": 2011,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 19,
        "study_start_min": 58,
        "study_start_second": 14,
    },
    "n11": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 36,
        "study_start_second": 46,
    },
    "n1": {
        "study_start_year": 2009,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 6,
        "study_start_second": 3,
    },
    "n2": {
        "study_start_year": 2009,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 19,
        "study_start_min": 12,
        "study_start_second": 6,
    },
    "nfle10": {
        "study_start_year": 2010,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 23,
        "study_start_min": 50,
        "study_start_second": 31,
    },
    "nfle11": {
        "study_start_year": 2011,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 30,
        "study_start_second": 42,
    },
    "nfle12": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 40,
        "study_start_second": 41,
    },
    "nfle13": {
        "study_start_year": 2001,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 7,
        "study_start_second": 5,
    },
    "nfle14": {
        "study_start_year": 2001,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 21,
        "study_start_min": 46,
        "study_start_second": 43,
    },
    "nfle15": {
        "study_start_year": 1999,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 7,
        "study_start_second": 22,
    },
    "plm10": {
        "study_start_year": 2011,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 41,
        "study_start_second": 46,
    },
    "plm1": {
        "study_start_year": 2010,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 21,
        "study_start_min": 58,
        "study_start_second": 23,
    },
    "plm2": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 28,
        "study_start_second": 47,
    },
    "plm3": {
        "study_start_year": 2011,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 57,
        "study_start_second": 41,
    },
    "plm5": {
        "study_start_year": 2009,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 20,
        "study_start_min": 16,
        "study_start_second": 16,
    },
    "plm6": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 18,
        "study_start_min": 28,
        "study_start_second": 17,
    },
    "rbd10": {
        "study_start_year": 2008,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 9,
        "study_start_second": 22,
    },
    "rbd11": {
        "study_start_year": 2008,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 9,
        "study_start_second": 22,
    },
    "rbd12": {
        "study_start_year": 2008,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 21,
        "study_start_min": 52,
        "study_start_second": 54,
    },
    "rbd13": {
        "study_start_year": 2007,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 19,
        "study_start_second": 6,
    },
    "rbd16": {
        "study_start_year": 2008,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 22,
        "study_start_min": 15,
        "study_start_second": 16,
    },
    "rbd17": {
        "study_start_year": 2009,
        "study_start_month": 1,
        "study_start_day": 1,
        "study_start_hour": 21,
        "study_start_min": 54,
        "study_start_second": 31,
    },
}

# FREQUENCY
FREQUENCY = 512

# EEG_COLUMNS (Used for EEG channel averaging)
EEG_COLUMNS = [
    "Fp2-F4",
    "F4-C4",
    "C4-P4",
    "P4-O2",
    "F8-T4",
    "T4-T6",
    "FP1-F3",
    "F3-C3",
    "C3-P3",
    "P3-O1",
    "F7-T3",
    "T3-T5",
    "C4-A1",
    "ROC-LOC",
    "LOC-ROC",
    "LOC / A2",
    "ROC / A1",
    "C3-A2",
    "O1-A2",
    "O2-A1",
    "ROC",
    "LOC",
    "F3A2",
    "F4A1",
    "C3A2",
    "C4A1",
    "F2-F4",
    "F1-F3",
    "LOC-A1",
    "ROC-A2",
]

# SLEEP_STAGES (diCtionary mapping sleep stage to ordinal number)
SLEEP_STAGES = {"W": 0, "S1": 1, "S2": 2, "S3": 3, "S4": 4, "R": 5}

# CONDITION_TO_BINARY (dictionary for dummy encoding of conditions analyzed)
CONDITION_TO_BINARY = {
    "Normal": [0, 0, 0, 0],
    "Nocturnal Frontal Lobe Epilepsy": [0, 0, 1, 0],
    "Insomnia": [0, 1, 0, 0],
    "Periodic Leg Movement": [0, 0, 0, 1],
    "REM Behavior Disorder": [1, 0, 0, 0],
}
